version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
    secrets:
      - mongo_password
      - discinstock_user_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
      - MONGO_INITDB_DATABASE=discinstock
      - MONGO_NON_ROOT_USERNAME=discinstock_user
      - MONGO_NON_ROOT_PASSWORD_FILE=/run/secrets/discinstock_user_password
    command: ["--bind_ip_all"]

  spider:
    image: discinstock_spider:stage
    ports: 
      - "60002:8000"
    depends_on:
      - api
    secrets:
      - api_username
      - api_password
      - guru_api_key
      - guru_api_secret
    environment:
      - API_URL=http://api:8000
      - API_USERNAME_FILE=/run/secrets/api_username
      - API_PASSWORD_FILE=/run/secrets/api_password
      - GURU_API_KEY_FILE=/run/secrets/guru_api_key
      - GURU_API_SECRET_FILE=/run/secrets/guru_api_secret
      - CRAWL_INTERVAL=3600
      - LOG_LEVEL=INFO
      - ENABLE_DISC_ITEM_FLIGHT_SPEC_PIPELINE=True

  api:
    image: discinstock_api:stage
    ports: 
      - "60001:8000"
    depends_on: 
      - mongo
    secrets:
      - discinstock_user_password
      - jwt_secret_key
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=discinstock
      - MONGO_NON_ROOT_USERNAME=discinstock_user
      - MONGO_NON_ROOT_PASSWORD_FILE=/run/secrets/discinstock_user_password
      - FORWARDED_ALLOW_IPS=app
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - JWT_SECRET_KEY_FILE=/run/secrets/jwt_secret_key
      - JSON_LOGS=1
      - LOG_LEVEL=DEBUG
  app:
    image: discinstock_app:stage
    ports:
      - "60000:80"
    depends_on:
     - api

secrets:
  mongo_password:
    external: true
  discinstock_user_password:
    external: true
  jwt_secret_key:
    external: true
  api_username:
    external: true
  api_password:
    external: true
  guru_api_key:
    external: true
  guru_api_secret:
    external: true

volumes:
  mongo-data:

networks:
  default:
    name: discinstock
    external: true
