version: "3.9"

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
    secrets:
      - mongo_password
      - discinstock_user_password
    networks:
      - discinstock_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
      - MONGO_INITDB_DATABASE=discinstock
      - MONGO_NON_ROOT_USERNAME=discinstock_user
      - MONGO_NON_ROOT_PASSWORD_FILE=/run/secrets/discinstock_user_password
    command: ["--bind_ip_all"]

  spider:
    image: discinstock_spider:stage
    ports: 
      - "60002:8000"
    depends_on:
      - mongo
    secrets:
      - discinstock_user_password
    networks:
      - discinstock_network
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=discinstock
      - MONGO_NON_ROOT_USERNAME=discinstock_user
      - MONGO_NON_ROOT_PASSWORD_FILE=/run/secrets/discinstock_user_password
      - CRAWL_INTERVAL=3600

  api:
    image: discinstock_api:stage
    ports: 
      - "60001:8000"
    depends_on: 
      - mongo
    secrets:
      - discinstock_user_password
    networks:
      - discinstock_network
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=discinstock
      - MONGO_NON_ROOT_USERNAME=discinstock_user
      - MONGO_NON_ROOT_PASSWORD_FILE=/run/secrets/discinstock_user_password
      - FORWARDED_ALLOW_IPS=app

  app:
    image: discinstock_app:stage
    ports:
      - "60000:80"
    depends_on:
     - api
    networks:
     - discinstock_network

secrets:
  mongo_password:
    external: true
  discinstock_user_password:
    external: true

networks:
  discinstock_network:

volumes:
  mongo-data: